### ISSUE TITLE
Ist die Datenbank aktuell nicht verfügbar?

### ISSUE THREAD

**Issue by bfu-meister** [haumacher/phoneblock#11]
Die Fritzbox kann das Phonebook nicht synchronisieren.. ständig Fehler das ich die Logindaten prüfen soll. 
"Die Aktualisierung ist gescheitert. Bitte überprüfen Sie die Benutzerdaten.(11)"
Login wurde sogar schon neu gemacht.. trotzdem kann man nicht synchronisieren. Auf der Homepage ann ich mich mit den Daten einloggen.. seltsam.

**Comment by haumacher** [comment]
Ich sehe in den Log-Dateien Einträge der Bauart 

```
[2022-11-01 09:46:21] [info] WARN: Invalid password (length 20) for user: te...@24-mail...
```

Das deutet darauf hin, dass das von der Fritz!Box übermittelte Passwort tatsächlich nicht mit dem gespeicherten Hash übereinstimmt. Die Länge (20 Zeichen) scheint zu stimmen, da [PhoneBlock](https://phoneblock.haumacher.de/) Passwörter mit dieser Länge generiert.

Allerdings scheint die Fritz!Box manchmal Adressbücher bei Änderung nicht richtig zu aktualisieren. Wenn gar nichts anderes hilft, versuche bitte folgendes:

 * Lösche das PhoneBlock-Adressbuch
 * Starte die Fritz!Box neu
 * Richte das Adressbuch erneut ein

Wenn das auch nicht hilft, kontaktiere mich bitte per E-Mail (siehe [PhoneBlock FAQ](https://phoneblock.haumacher.de/phoneblock/faq.jsp) ganz unten).

**Comment by bfu-meister** [comment]
Telefonbuch gelöscht und neu eingerichtet.. nun läufts. Danke

**Comment by haumacher** [comment]
Super, dann wünsche ich entspanntes Telefonieren :-)
