### ISSUE TITLE
Registrierung: Passwort wird nicht angezeigt

### ISSUE THREAD

**Issue by geimist** [haumacher/phoneblock#111]
Ich wollte ein neues Benutzerkonto anlegen. Nach dem Eingeben des Bestätigungscodes ist man zwar eingeloggt, aber das generierte Passwort wird nicht angezeigt. 
Auch ein Klick auf `neues Passwort erzeugen` hat lediglich den Effekt wie das Neuladen der Seite.

**Comment by haumacher** [comment]
Ja ist defekt. Workaround: Nach "Passwort zurücksetzen" auf die Seite https://phoneblock.net/phoneblock/setup.jsp wechseln - dort wird es dann angezeigt.

**Comment by haumacher** [comment]
Ich glaube, ich habe das Problem gefixt - ganz schön kompliziert, in allen Fällen eine vernünftige Folgeseite nach einem Login/Signup/Password-Reset zu zeigen. Kannst Du das nochmal testen (ist live auf https://phoneblock.net/)?

**Comment by geimist** [comment]
Ja, läuft. Auch beim Zurücksetzen des Passwortes.

Ohne Wertung: 
Mir ist aufgefallen, dass in dem Feld jetzt nicht die CardDAV URL angezeigt wird. Das war unter [./phoneblock/setup.jsp](https://phoneblock.net/phoneblock/setup.jsp) noch der Fall.

**Comment by geimist** [comment]
Irgendetwas scheint noch nicht zu passen.
Wenn ich mich nach der Registrierung auslogge, bzw. ausgeloggt wurde, wird anschließend der vorher angezeigt Passwort nicht akzeptiert. 
Registriert man sich dann mit der Mailadresse erneut, bleibt die User-ID erhalten und auch die angelegten ABs sind noch da (man kann also die Registrierung als Passwortreset nutzen, was gut ist). Gleicher Effekt besteht auch, wenn ich nach der Registrierung das Passwort neu erstellen lasse.
