### ISSUE TITLE
Fehler 404 bei WebGUI / More / Report an issue

### ISSUE THREAD

**Issue by Enkidu70** [haumacher/phoneblock#15]
Wenn ich im WebGUI unter More auf [Report an issue](https://phoneblock.haumacher.de/phoneblock/link/new-issue) gehe, bekomme ich nur "Seite nicht gefunden" angezeigt.

Ich würde mal vermuten wollen, ich sollte hier bei GitHub rauskommen?

![grafik](https://user-images.githubusercontent.com/1456895/213586572-62c433c7-c101-4230-8b8f-8c15045be5ec.png)

**Comment by haumacher** [comment]
Mit 20d1d8aa4b059caccc55bf2f18b28c74b723c277 behoben.
