### ISSUE TITLE
Feature Request: Telefonspam-Portale auf gemeldete Rufnummer abfragen

### ISSUE THREAD

**Issue by Enkidu70** [haumacher/phoneblock#18]
Beim Neueintrag einer Nummer sollte diese via den gängigen Portalen automatisch geprüft werden. Da diese i.a.R. eindeutige URIs für die abzufragenden Rufnummern verwenden, könnte man dies per simplen https-GET und einfaches Durchsuchen des Ergebnisses einfach bewerkstelligen.

Bsp.:
* https://www.tellows.de/num/0681936515856

Im Code sieht das dann so aus:
* `<h4>Achtung, 0681936515856 ist negativ bewertet. Anrufschutz empfohlen!</h4>`

Bei https://www.werruft.info/telefonnummer/0681936515856/ ist es ähnlich...

**Comment by haumacher** [comment]
Gute Idee - bei wachsender Community immer effektiver. Am Anfang hat das nichts genutzt, weil niemand die [PhoneBlock-Webseite](https://phoneblock.haumacher.de/) tatsächlich aktiv zum Suchen benutzt hat. Aber mittlerweile könnte das tatsächlich helfen.

**Comment by Enkidu70** [comment]
Ich meine das generell. Wenn wer per Blocklistentelbucheintrag eine Nr. meldet, vom System aus bei bspw. Tellows die Nr. abfragen. Wenn klar ist, ist Spam, sofort auf die Liste. Wenn nicht, wie bisher.

**Comment by haumacher** [comment]
Wurde mit 4ba5fab70b8df1a10fb5ac8541e41a1c1ad40416 umgesetzt. Die PhoneBlock-Suche führt jetzt eine Meta-Suche auf anderen Bewertungsportalen durch und zeigt Bewertungen von dort an. Zusätzlich kann man auch eigenen Bewertungen auf der PhoneBlock-Seite abgeben. Ausprobieren: [PhoneBlock](https://phoneblock.haumacher.de/phoneblock/) aufrufen und im Such-Feld ganz oben eine (SPAM-)Telefonnummer eingeben und suchen.
