### ISSUE TITLE
Bitte auf Whitelist setzen

### ISSUE THREAD

**Issue by MarkyMarkDE** [haumacher/phoneblock#27]
Ständig werden
0
00
000
0000
in die Blockliste eingetragen und gesperrt, doch man kann doch nicht so pauschal sperren, oder doch? Denke diese Ziffern werden automatisch eingetragen, durch den Crawler für tellows.

Vielleicht mal auf eine Whitelist oder ignore Liste setzen und auch die ganzen sehr widersprüchlichen Kommentare löschen.

**Comment by haumacher** [comment]
Wird mit #28 automatisch ignoriert.

**Comment by MarkyMarkDE** [comment]
super, bringe das nur noch dem Crawler bei :wink:
die Nummern wurden immer von Extern eingetragen

**Comment by MarkyMarkDE** [comment]
Sorry, das scheint nicht zu funktionieren
https://phoneblock.haumacher.de/phoneblock/nums/0000

**Comment by haumacher** [comment]
Die "Nummer" 0000 ist kein Präfix einer anderen Nummer, daher wird sie "akzeptiert". Schadet aber nicht, da sie keiner echten Telefonnummer entspricht - ist einfach Unsinn in der Blocklist - wie vielleicht andere Nummer darin auch... "0" und "00" tauchen jetzt aber nicht mehr auf.

**Comment by haumacher** [comment]
Wenn Dich das stört, kannst Du diese "Nummer" auf Deine persönliche Whitelist setzten.

**Comment by MarkyMarkDE** [comment]
0000
000
00
0

ist wirklich absoluter Unsinn.

**Comment by haumacher** [comment]
Korrekt - und 0 und 00 werden jetzt auch effektiv verhindert... :-)

**Comment by MarkyMarkDE** [comment]
> Korrekt - und 0 und 00 werden jetzt auch effektiv verhindert... :-)

nimmst Du bitte noch die 0000 plus Kommis raus?
Ich versuche nämlich in den Standardeinstellungen einen Bug zu finden, den ich leider schon länger habe und nicht weiß, ob die FB murkst oder die Blockliste ...

**Comment by haumacher** [comment]
OK weil Du's bist - ich habe 0000 und 000 auf die globale Whitelist gesetzt - sollten nach dem nächsten Update aus deiner Blocklist verschwinden. Die Kommentare auf der Webseite kann ich nicht löschen, weil die automatisch durch den Crawler reinkommen - aber auf der Blocklist sollten die Nummern jetzt nicht mehr auftauchen.

**Comment by MarkyMarkDE** [comment]
> OK weil Du's bist - ich habe 0000 und 000 auf die globale Whitelist gesetzt - sollten nach dem nächsten Update aus deiner Blocklist verschwinden. Die Kommentare auf der Webseite kann ich nicht löschen, weil die automatisch durch den Crawler reinkommen - aber auf der Blocklist sollten die Nummern jetzt nicht mehr auftauchen.

Du könnest ja diese "globale Whitelist" auch auf den Crawler anwenden, dass dieser derartige Nummern plus Kommis ignoriert und nicht mehr an deine Datenbank übermittelt oder ein weiteres Script, was sowas im Nachgang wieder rauslöscht ...

**Comment by MarkyMarkDE** [comment]
> OK weil Du's bist - ich habe 0000 und 000 auf die globale Whitelist gesetzt - sollten nach dem nächsten Update aus deiner Blocklist verschwinden. Die Kommentare auf der Webseite kann ich nicht löschen, weil die automatisch durch den Crawler reinkommen - aber auf der Blocklist sollten die Nummern jetzt nicht mehr auftauchen.

Du wirst es nicht glauben: seit du die
0
00
000
0000

aus der Blacklist raus und in die globale Whitelist aufgenommen hast, ist mein "Bug" weg!
Demnach hatte die Fritz!Box mit Ihrer Sortierung "Nummer ist in Blacklist" scheinbar Recht.

Lustig ist nur, dass die Festnetznummer von diesem Kontakt korrekt nie geblockt war.
Nur aber die zum gleichen Kontakt gespeicherte Handynummer wurde falsch "deklariert" und somit auf den falschen AB umgeleitet, verstehen muss ich das nicht.

**Comment by haumacher** [comment]
OK - was auch immer die Fritz!Box hier tut, [PhoneBlock](https://phoneblock.haumacher.de/phoneblock/) ist also erst mal "aus dem Schneider" :-)

**Comment by MarkyMarkDE** [comment]
> OK - was auch immer die Fritz!Box hier tut, [PhoneBlock](https://phoneblock.haumacher.de/phoneblock/) ist also erst mal "aus dem Schneider" :-)

da ja nun 0, 00, 000 und 0000 auf der globalen Whitelist stehen, ist PhoneBlock in der Tat aus dem Schneider :wink:

**Comment by MarkyMarkDE** [comment]
Sei doch bitte so nett und nimm die

**0** - https://phoneblock.haumacher.de/phoneblock/nums/0

**00** - https://phoneblock.haumacher.de/phoneblock/nums/00

**00000** - https://phoneblock.haumacher.de/phoneblock/nums/00000

**000000** - https://phoneblock.haumacher.de/phoneblock/nums/000000

**0000000** - https://phoneblock.haumacher.de/phoneblock/nums/0000000

**00000000** - https://phoneblock.haumacher.de/phoneblock/nums/00000000

- und - 

**000000000** - https://phoneblock.haumacher.de/phoneblock/nums/000000000 

auch in die globale Whitelist auf, wäre echt nett 🤗

**Comment by haumacher** [comment]
OK, done - auf der weißen Liste... :-)

**Comment by MarkyMarkDE** [comment]
> OK, done - auf der weißen Liste... :-)

Super! Vielen, lieben Dank. Dann kann ich diese Nummern jetzt aus meiner Whitelist löschen :)
