### ISSUE TITLE
Spam-Anrufe über Cloud-Anrufbeantworter abfangen

### ISSUE THREAD

**Issue by haumacher** [haumacher/phoneblock#36]
## Problem
In ein Fritz!Box-Telefonbuch passen je nach Speicherart und Fritz!Box-Modell um die 3.000 Telefonnummern. Die aktuelle Block-Liste umfasst mehr als 11.000 Nummern mit einer stark steigenden Tendenz. Eine gute Auswahl der Nummern zu treffen, die tatsächlich in die Blockliste geladen werden wir zunehmend schwieriger. Da die Telefonbuchsynchronisierung einmal in der Nacht stattfindet, hat man eine Verzögerung von der Spam-Meldung bis zur effektiven Sperrung der Nummer von bis zu 24h. 

## Lösung
Die Spam-Erkennung und Rufbehandlung soll in einem Anrufbeantworter stattfinden, der extern an die Fritz!Box "angeschlossen" wird. Der Anrufbeantworter prüft bei einem ankommenen Anruf, ob der Anrufer in der Spam-Datenbank enthalten ist, und nimmt nur genau dann das Gespräch an. Damit lassen sich die folgenden Punkte leicht adressieren:

* Verwaltung von beliebig großen Blocklisten. Die Liste muss nicht mehr in die Fritz!Box geladen werden.
* Sofortige Blockierung einer Nummer, sobald genügend Spam-Meldungen für die Nummer eingegangen sind. Die Nummern müssen nicht in einem nächtlichen Synchronisierungslauf in die Fritz!Box geladen werden, sondern der Anrufbeantworter gleicht eine anrufende Nummer direkt mit der Blockliste ab.
* Garantiert keine Blockierung von Nummern, die der Nutzer lokal in sein Telefonbuch eingetragen hat. Der Anrufbeantworter kann erkennen, dass der Nutzer für eine Nummer einen eigenen Telefonbucheintrag hinterlegt hat und ignoriert alle Anrufe von Anrufern aus dem lokalen Telefonbuch.
* Keine Verlangsamung der Benutzeroberfläche der Fritz!Box durch riesige Telefonbücher. Der Anrufbeantworter prüft nur Nummern, die tatsächlich anrufen. 
* Erkennung von noch aktiven Spam-Nummern. Bisher kann PhoneBlock nur durch manuelle Meldung von Nummern durch Nutzer erkennen, dass eine Spam-Nummer noch aktiv ist. Ist eine Nummer aber einmal blockiert, ergibt es für Nutzer keinen Sinn mehr, eine Spam-Meldung zu machen und PhoneBlock kann nicht erkennen, ob eine Nummer noch eine aktive Quelle von Spam-Anrufen ist. Da der Anrufbeantworter ankommende Anrufe, die sich nicht im Telefonbuch des Nutzers befinden aktiv überprüft, kann diese Prüfung genutzt werden, um aktive Spam-Nummer zu erkennen.
* Beschäftigung von Spam-Anrufern. Wird eine Nummer nur blockiert, tut das einem "Spam-Anbieter" nicht weh, da der Telefoncomputer direkt die nächste Nummer wählt. Teuer wird es für den Spammer erst, wenn der Anruf angenommen und an einen "Call-Center-Mitarbeiter" übergeben wird. Ziel des PhoneBlock-Anrufbeantworters ist es daher, Spam-Anrufe anzunehmen, sich nicht als Anrufbeantworter zu erkennen zu geben und möglichst lange mit dem Anrufer zu "reden" - natürlich ohne das Wort "ja" in den Mund zu nehmen. 

## Umsetzung

An einer Fritz!Box (und anderen Telefonanlagen) lassen sich VOIP-Telefoniegeräte anmelden (VOIP=Voice-over-Internet-Protocol). VOIP-Telefone gibt es relativ teuer als Hardware zu kaufen, ein VOIP-Telefoniegerät lässt sich aber auch rein in Software implementieren. 

Der PhoneBlock-Anrufbeantworter ist ein solches rein in Software realisiertes Telefoniegerät, dass an der Fritz!Box angemeldet werden kann. Hierfür benötigt man keinen eigenen Rechner, der 7/24 läuft, sondern der PhoneBlock-Anrufbeantworter läuft in der PhoneBlock-Cloud und kann von dort (über das Internet) an der eigenen Fritz!Box angemeldet werden. (Wenn man einen eigenen Rechner hat, der 7/24 online ist, kann man den PhoneBlock-Anrufbeantworter natürlich auch dort installieren und selber betreiben - ist ja open-source). 

## Offene Punkte 

* [x] Konfigurations-GUI, mit der ein Anrufbeantworter erzeugt, angemledet, eingeschaltet, ausgeschaltet und wieder  gelöscht werden kann.
* [x] Ausschluss von Nummern, die sich im Telefonbuch des Nutzers befinden.
* [x] Zählen von abgefangenen Spam-Anrufen pro Nutzer/Anrufbeantworter.
* [X] Feedback beim Registrieren/Einschalten eines Anrufbeantworters.
* [x] Übersicht über die Zeit, die der Anrufbeantworter insgesamt mit Spam-Anrufern geredet hat.
* [x] Liste von abgefangenen Spam-Anrufen mit Nummer des Anrufers, Uhrzeit und Dauer des Anrufs.
* [x] Hilfe-Seiten für die Einrichtung eines PhoneBlock-Anrufbeantworters.
* [x] #39
* [ ] #40

**Comment by MegaV0lt** [comment]
Was noch rein müsste ist meiner Meinung nach eine einstellbare Zeit, nach der Spam-Nummern wieder entfernt werden. Wenn eine Nummer z. B. drei Jahre nicht mehr gesehen wurde oder so

**Comment by haumacher** [comment]
@MegaV0lt Vielleicht magst Du Dich am Beta-Test beteiligen? Ich habe ein Test-System mit der Anrufbeantworter-Funktionalität aufgesetzt (sieht aus wie die Hauptseite, man muss aber einen separaten Account erstellen): https://phoneblock.net/pb-test/anrufbeantworter/ - Die SPAM-Datenbank wird aber von der Hauptseite verwendet.

**Comment by pulsarclarinetokrabee** [comment]
Wäre bei der aktuellen Umsetzung einer lokalen Installation der Betrieb des Anrufbeantworter auf einem Raspberry Pi möglich?

**Comment by FichtnerS** [comment]
> > Wäre bei der aktuellen Umsetzung einer lokalen Installation der Betrieb des Anrufbeantworter auf einem Raspberry Pi möglich?
> 
> Ja, definitiv. Wenn man https://github.com/haumacher/phoneblock/tree/answerbot/phoneblock-ab baut, fällt ein JAR heraus, mit dem man einen laufenden Anrufbeantworter hat. Leider muss man dafür auch noch https://github.com/haumacher/mjSIP vorher bauen, um die dafür nötige SIP Bibliothek zu bekommen.

Hallo.
Gibt es eine Anleitung wie man sich das selbst zusammen bauen kann? Ich kenne mich leider nur sehr rudimentär mit Java auf (Schulniveau).

Gibt's das eventuell auch schon als Docker oder ist das geplant?

Vielen Dank!

**Comment by haumacher** [comment]
@FichtnerS Distribution for RaspberryPi ist geplant, aber hat aktuell nicht die höchste Priorität. Das selber zu betrieben ist nochmal um ein Vielfaches komplizierter, als den Cloud-Service zu nutzen. Aktuell muss zuerst dieser Dienst "rock-solid" funktionieren, bevor man das dezentral installieren sollte - das ist aktuell nur für Entwickler zu empfehlen, wenn eine Mitarbeit an dem Projekt geplant ist.

Beta-Tester für den Cloud-Dienst helfen aktuell mehr. 

Test System: https://phoneblock.net/pb-test/anrufbeantworter/ (erfordert separate Anmeldung)

**Comment by dm82m** [comment]
@haumacher ich hatte bisher die telefonbuch variante im einsatz und bin jetzt auf den die testversion des anrufbeantworters  gegangen und teste das. ich habe ein mesh setup mit einer zweiten fritzbox im haus, auf der auch telefonie eingerichtet ist. dafür muss ich dann vmtl. einen zweiten anrufbeantworter erstellen oder? oder kann ich die identischen daten des ersten nutzen?

**Comment by haumacher** [comment]
Zu 1: Das Anrufbeantworter-Testsystem nutzt tatsächlich die Blockliste der Live-Version über die API.

Zu 2: Siehe 1 - die Blockliste wird vollständig durch die Live-Version verwaltet - Melden über negative Bewertung auf der Webseite.

Zu 3: Ja, das Telefon kann ganz kurz klingeln - da kann man wohl nichts gegen machen, weil der AB ja wie ein normales Telefon reagiert. Die Box lässt die Telefone so lange klingeln, bis eines der Telefone den Anruf annimmt.

**Comment by haumacher** [comment]
Funktion ist live: https://phoneblock.net/phoneblock/anrufbeantworter/

Fehlendes wird nachgeliefert (#40).
