### ISSUE TITLE
Unterstützung von Mobiltelefonen

### ISSUE THREAD

**Issue by haumacher** [haumacher/phoneblock#4]
Aktuell kann man die Blocklist nur als Adressbuch in die Kontakte aufnehmen, aber nicht blockieren. Eine App sollte sie Synchronisierung übernehmen und auf Wunsch Anrufe blockieren.

**Comment by kefor** [comment]
Hi, 

hier gibt es eine interessante App, die das wohl erledigen könnte. Leider bekomme ich es mit dem Username Passwort nicht in die Datenbank eingelesen. 

https://github.com/aj3423/SpamBlocker

**Comment by haumacher** [comment]
Coole Sache, die Beschreibung in #87 scheint hier schon eine Lösung zu bieten.
