### ISSUE TITLE
Anmeldung an phoneblock.net mit E-Mail-Adresse funktioniert nicht

### ISSUE THREAD

**Issue by jens-ey** [haumacher/phoneblock#42]
Ich habe es zwei Mal versucht, es gelang mir nicht, mich an dem Konto wieder anzumelden nach der Registrierung mittels einer Mail-Adresse. Sign-in mit Google problemlos.

**Comment by jwgn** [comment]
So ist das ja auch nicht gedacht. Richtig lesen:

`Verwende den Benutzernamen, den Du bei der [Registrierung mit E-Mail-Adresse erhalten hast.`

**Comment by jens-ey** [comment]
Hi,
ich habe den Benutzernamen verwendet, der nach der Registrierung angezeigt worden ist (31512f24-1406-4938-b9f7-xxxxxxxxxxx) zusammen mit dem vom Portal vergebenen Kennwort.
Ich habe danach mit einer anderen Mail-Adresse noch eine Registrierung durchgeführt und mit den dabei erhaltenen Credentials konnte ich mich ebenso wenig am Portal wieder anmelden. Name und PW sind jeweils per Copy&Paste bzw. vom Passwort-Manager eingetragen worden.
Sorry, ich sehe hier keinen Fehler bei mir. Da ich aber gerade die Gelegenheit genutzt habe, es noch einmal (mit einer weiteren) Mailadresse zu testen und es dieses Mal keine Probleme gab, belassen wir es wohl dabei.

**Comment by jens-ey** [comment]
Nicht reproduzierbar

**Comment by jens-ey** [comment]
Nicht reproduzierbar
