### ISSUE TITLE
RSS-Feed für Updates?

### ISSUE THREAD

**Issue by BeyondVertical** [haumacher/phoneblock#43]
Hallo,

zunächst einmal: vielen Dank für die Arbeit!
Echt sehr nützlich.

Dann zu meiner Frage:
Könnte man für Updates, die aktuell ja wohl bei Facebook gepostet werden, z.B. auch einen RSS-Feed einrichten?
Ich nutze kein Facebook, würde aber trotzdem gerne über Updates informiert werden.

**Comment by haumacher** [comment]
Gute Idee - ich habe mal rss.app ausprobiert und die FaceBook-Seite in einen Feed umgewandelt: https://rss.app/feeds/2BQDpMNxPek9Yal2.xml kannst Du damit was anfangen?

**Comment by haumacher** [comment]
Mit der PhoneBlock-FaceBook-Grupp geht das auch aber da sieht man leider keine Antworten: https://rss.app/feed/MQjuX1yriRbJLGz8

**Comment by BlackScreen** [comment]
> Gute Idee - ich habe mal rss.app ausprobiert und die FaceBook-Seite in einen Feed umgewandelt: https://rss.app/feeds/2BQDpMNxPek9Yal2.xml kannst Du damit was anfangen?

Ja, damit kann ich was anfangen. Danke!

**Comment by BlackScreen** [comment]
Also ich glaube das war wohl leider keine Langzeit-Lösung. Der Feed ist leer und bei mir kam das im Reader:

![image](https://github.com/haumacher/phoneblock/assets/17316492/172c2d45-05ff-47c1-8401-84e8661aa0f8)

**Comment by haumacher** [comment]
Ok, danke - was ein Mist... ich schau mal, was sich machen lässt...

Am 20. Februar 2024 23:33:48 MEZ schrieb BlackScreen ***@***.***>:

**Comment by Revan335** [comment]
Gibt es irgendwelche Neuigkeiten?

**Comment by haumacher** [comment]
Leider nein - ich habe bisher keine einfache Möglichkeit gefunden, den Facebook-Kanal in einen Feed umzuwandeln. Die Alternative wäre Neuigkeiten auch direkt auf der PhoneBlock-Seite zu posten, das ist aber mit nicht vernachlässigbarem Aufwand verbunden...

**Comment by haumacher** [comment]
Es gibt doch Neuigkeiten: PhoneBlock hat jetzt seine eigene Nachrichtenseite mit einem eigenen RSS-Feed: https://news.phoneblock.net/feed

Nachdem die faschistoide Zensur-KI mehrere meiner Beiträge vollkommen unbegründet gelöscht hat hatte ich die Faxen dicke: https://news.phoneblock.net/2024/12/14/eigene-phoneblock-nachrichtenseite/

**Comment by haumacher** [comment]
Der RSS-Feed auf der Hauptseite ist mit dem letzten Update jetzt live.
