### ISSUE TITLE
Weitere Rufnummern für PhoneBlock

### ISSUE THREAD

**Issue by dontobi** [haumacher/phoneblock#44]
Hallo zusammen

Ich bin durch Zufall auf dieses Projekt gestoßen und möchte an alle Beteiligten ein riesen Dankeschön aussprechen.

Ich selber weiß, wie aufwendig es sein kann eine solche Liste zu pflegen. Ich pflege nämlich selber eine Liste hier auf GitHub.

Um diese Liste geht es auch. Da ich so einige Rufnummern zusammengetragen habe und gerade wenig Zeit habe, war es mir nicht möglich alle auf der PhoneBlock Seite zu suchen. Ich gehe aber davon aus, dass die meisten bereits geblockt sind.

Nun aber zu meiner Frage... Wäre es möglich die Rufnummern aus meiner Liste bei PhoneBlock ein zu pflegen?

Anbei der Link zu meiner Repo: https://github.com/dontobi/SpamCalllist

Solle es nicht möglich sein, die von mir gesammelten Rufnummern automatisiert bei PhoneBlock ein zu pflegen, werde ich versuchen nach und nach meine Rufnummern abzuarbeiten.

Gruß aus dem Rheinland
Tobi

PS: ich werde mich dann gleich bei PhoneBlock anmelden und es zukünftig auch nutzen. Abgesehen davon werde ich dann ein Update auf meinem privaten Blog veröffentlichen. Denn dort habe ich bereits einen Beitrag veröffentlicht, wie man Spam Anrufe mit meiner Liste blocken kann. Somit möchte ich dazu beitragen PhoneBlock populärer zu machen.

**Comment by haumacher** [comment]
Hallo @dontobi,

schön, dass Dir [PhoneBlock](https://phoneblock.net) gefällt. Ich habe mir die Liste aus Deinem Repository angeschaut. Leider hat PhoneBlock keine Import-Möglichkeit. Aber ich habe einen manuellen Abgleich mit der Datenbank durchgeführt, den ich hier dokumentiere - falls ich mich mal wieder daran erinnern muss, wie das geht :-)

Nummern aus dem Telefonbuch-XML extrahieren:
```
sed 's/.*<number[^>]*>//' ~/Downloads/fritzbox_export.xml | sed 's|</number>||' | sed 's/.*<.*//' | sed 's/\+/00/' | sort -u | grep -v '*'
```
Dabei ist zu beachten, dass die PhoneBlock-Datenbank keine Wildcards (Nummern mit *) zulässt. PhoneBlock generiert solche Wildcards selbstständig, wenn es viele Spam-Reports von benachbarten Nummern gibt.

Es verbleiben 374 Nummern. CSV-Import in eine neue Tabelle `NUMIMPORT`.

Davon befinden sich 49 Nummer aktuell nicht auf der Blockliste. Allerdings sind von diesen 49 Nummern PhoneBlock 31 bereits bekannt, wurden aber wieder von der Blockliste aussortiert, weil länger keine SPAM-Reports mehr eingegangen sind. Überig bleiben diese Nummern, die "neu" sind:

```
SELECT * FROM NUMIMPORT n 
LEFT OUTER JOIN SPAMREPORTS s 
ON n.PHONE = s.PHONE 
LEFT OUTER JOIN OLDREPORTS o 
ON n.PHONE = o.PHONE 
WHERE s.PHONE IS NULL AND o.PHONE IS NULL ;
```

```
002348109796250
00249909866115
0027712838258
003250660514
0033235869346
00393343611334
00447798956415
00447873024449
00447888882946
00447888886071
00639538217566
00918279524253
00919355616335
0096892612742
015510952694
017668779853
0589354638
0612456484
```

Diese müsste man bei Gelegenheit mal in das Nummernsuchfeld von PhoneBlock eingeben, damit eine Suche nach Kommentaren auf anderen Seiten durchgeführt wird. Allerdings ist der Traffic auf der Seite gerade so hoch, dass die Meta-Suche ins Leere läuft, weil zu viele Anfragen gestellt werden.

**Comment by dontobi** [comment]
Danke und ich habe die letzten beiden Tage alle Nummern von Hand einmal eingegeben und über meine Fritzbox eingetragen (nur die, die gefehlt haben).

Ich werde dann an dieser Stelle das Issue zu machen und kommentiere demnächst nochmals wenn ich den neuen Beitrag auf meinem Blog veröffentlicht habe. Darin werde ich dann PhoneBlock bewerben und hoffe darüber neue Nutzer für PhoneBlock zu erschließen.
