### ISSUE TITLE
Update Android Tutorial

### ISSUE THREAD

**Issue by SaltyAimbOtter** [haumacher/phoneblock#51]
Thank you for your work on this project!

While following the installation guide for Android, I noticed that the suggested app is no longer available in the Google Player Store. On [GitHub](https://github.com/deependhulla/opensync) it is marked as "archived" as of Jul 11, 2023. 

Therefore I suggest updating the installation tutorial to the upstream project of Open Sync, DAVx⁵. The tutorial could either suggest using the PlayStore version (which costs money) or downloading the latest release for free from [GitHub](https://github.com/bitfireAT/davx5-ose/releases).

**Comment by haumacher** [comment]
@SaltyAimbOtter are you willing to contribute an updated installation guide?

**Comment by haumacher** [comment]
The easiest was would be to write a new guide e.g. on https://medium.com and I could then link this article instead of the built-in setup guide. However, filing a PR is also welcome.

**Comment by haumacher** [comment]
On Facebook, a user also suggested to install DAVx from f-droid.org, where it is free - but adding the alternative store is also somewhat inconvenient:  https://f-droid.org/de/packages/at.bitfire.davdroid/

**Comment by SaltyAimbOtter** [comment]
Installing f-droid is just an extra step - users will have to install from an APK anyways if they want it for free. So it does not really make much sense to force them to install F-Droid.

I will open a PR.

**Comment by LizenzFass78851** [comment]
An alternative app to the `open sync` app would be [PeopleSync CardDAV Client](https://play.google.com/store/apps/details?id=com.messageconcept.peoplesyncclient)

I tested it successfully. see discussion #59

**Comment by SaltyAimbOtter** [comment]
Thank you for the comment, it seems that this would be a better option since it is in the Play Store! It is technically also DAVx⁵ according to https://github.com/messageconcept/PeopleSyncClient and therefore GPLv3.
Would you like to open the PR instead, since you already made all the screenshots anyways?

**Comment by LizenzFass78851** [comment]
> Would you like to open the PR instead, since you already made all the screenshots anyways?

Yes, I do that when I find the time for it.

**Comment by SaltyAimbOtter** [comment]
Great, you can find the pages in src/main/webapp/setup-android.

**Comment by LizenzFass78851** [comment]
@SaltyAimbOtter Android tutorial is updated.  Therefore the issue is solved.

**Comment by haumacher** [comment]
New version is online: https://phoneblock.net/phoneblock/setup-android/
