### ISSUE TITLE
Projekt Name

### ISSUE THREAD

**Issue by KobeLAL** [haumacher/phoneblock#6]
Ich finde das Projekt gut gelungen. Hast du schonmal über einen anderen Namen nachgedacht? Man findet dein Projekt kaum über Google. Ich habs z.B. über einen Kommentar bei Heise unter einem anderen Programm gefunden.

**Comment by haumacher** [comment]
Ja, ich habe verpasst im Vorfeld eine Google-Recherche zu machen. Hättest Du einen Vorschlag für einen besseren Namen? 

Das Google-Ranking ist aber bereits dabei sich zu verbessern. Es war ein "harter Kampf" die Bots dazu zu bringen, die Seite zu schlucken. Zuerst habe ich versucht ihnen eine Sitemap.xml mit allen Nummer vorzuwerfen, leider ohne Erfolg. Danach habe ich  die Google-Update-API und Index-Now implementiert. Google ist seitdem eifrig dabei neue Seiten zu indizieren. Bing weigert sich aber immer noch standhaft, Seiten überhaupt abzufragen (nur Yandex kommt vorbei - ist aber eher irrelevant).

**Comment by KobeLAL** [comment]
Tatsächlich fällt mir spontan kein Name ein. Google denkt bei der Suche, man würde „Phonebloks“ suchen. Den Begriff kannte ich z.B. gar nicht.

**Comment by haumacher** [comment]
Google lernt aber langsam - Du kannst dabei helfen: Mach einen Post und setzte darin einen Link auf http://homepi:8081/phoneblock/

**Comment by KobeLAL** [comment]
Heißt, posten ich es in einem Forum, findet der Bot es irgendwann?

**Comment by haumacher** [comment]
Ja, ein Forum ist gut - wenn es öffentlich einsehbar ist. Dann findet es Google irgendwann und das verbessert das Ranking der Seite.

**Comment by bcutter** [comment]
Evtl. "Phone-Hole" in Anlehnung an Pi-Hole, welches auf DNS-Ebene Werbung und schädliche Inhalte blockt.

**Comment by haumacher** [comment]
Das Problem hat sich erübrigt - wer nach "PhoneBlock" sucht, bekommt jetzt die richtige Antwort.
