### ISSUE TITLE
Nummernsuche auf phoneblock.net: Unterschiedliche Formate liefern unterschiedliche Results

### ISSUE THREAD

**Issue by ignoreigor** [haumacher/phoneblock#62]
Hallo,

ersteinmal: tolles Projekt! Ich habe schon einige Male bei Freunden davon geschwärmt.

Kurze Frage: Die Nummernsuche auf der Homepage zeigt alternative Schreibweisen für die Nummern an. Jedoch liefern Suchen im E164-Format, internationales Format 00 bzw. nationales Format einer Nummer unterschiedliche Treffer. Ist das gewollt?

Sorry, wenn das schon mal diskutiert worden sein sollte. Ich habe mich bemüht eine Antwort zu finden.

**Comment by haumacher** [comment]
Hi, 

schön, dass Dir Phoneblock gefällt. Die unterschiedlichen Treffer je nach Nummernformat sind definitiv ein Bug. Muss ich schauen, woher das kommt. Würdest Du ein Ticket auf der Github-Seite anlegen?

Gruß Bernhard 

Am 13. März 2024 17:44:39 MEZ schrieb ignoreigor ***@***.***>:

**Comment by haumacher** [comment]
Sorry war ja Blödsinn, ist ja schonauf Github, habe nur in der Mail gesehen...

**Comment by haumacher** [comment]
Fixed with 9ba8eb080318d97eec4ab09338cbda43684a155b.

**Comment by haumacher** [comment]
Fixed with 9ba8eb080318d97eec4ab09338cbda43684a155b.
