### ISSUE TITLE
Gefälschte Mobilnummern blockieren

### ISSUE THREAD

**Issue by p0rys** [haumacher/phoneblock#70]
Moin Leute,

erstmal vielen Dank für die Arbeit die in dieses Projekt geflossen ist!

Leider haben meine Eltern und Großeltern aktuell ein großes Problem mit SPAM/SCAM Anrufen und ich versuche grade diese etwas in den Griff zu bekommen bevor noch irgendjemand eine Zeitschrift abonniert oder Geld an Microsoft überweist. Ich konnte das PhoneBlock Telefonbuch bereits erfolgreich in die FritzBoxen importieren, jedoch sind > 95% der Anrufe von irgendwelchen gefälschten Mobilnummern (meistens 01521*, manchmal auch 0163* oder 0176*). Leider lässt sich an diesen Nummern kein Muster erkennen (und ich sehe in der FritzBox auch die "reale" Nummer nicht) und ich würde ungern komplette Anbieter (z.B. 01521 Lycamobile) blockieren. Gibt es da schon irgendwelche Wege oder Möglichkeiten? Ich würde diese Nummer gerne direkt blocken und nicht erst nachdem sie bereits einmal angerufen haben, da sich die Nummer quasi niemals wiederholen...

**Comment by haumacher** [comment]
Hi,

ich dachte eigentlich, dass es nach den neusten Regelungen nicht mehr möglich ist aus dem Ausland inländische Nummern vorzutäuschen (vgl. https://www.telefonica.de/eu-roaming-verordnung.html). 

Was allerdings nach wie vor möglich ist, dass ein Profi-Spammer eine andere Rufnummer übermittelt, als eigentlich seinem Anschluss zugeordet ist (vgl. https://www.bundesnetzagentur.de/DE/Vportal/TK/Aerger/Faelle/Manipulation/start.html). Bisher ging ich davon aus, dass die Fritz!Box in diesen Fällen beide Nummern (die übermittelte und die eigentliche Anschlussnummer in der Anrufliste anzeigt, so wie in folgendem Beispiel):

![image](https://github.com/haumacher/phoneblock/assets/5607145/e6b6db3b-13c2-42ca-95eb-e3b77a9e95e6)

Welche der beiden Nummer die Box aber verwendet, um den Anruf zu blockieren oder umzuleiten, weiß ich leider nicht. Ich fürchte aber die Anrufbehandlung richtet sich nach der übertragen (also wahrscheinlich "gefälschten") Rufnummer.

**Comment by nillebor** [comment]
@p0rys,

warum sperrst du nicht einfach alle Rufnummern, welche nicht im Telefonbuch hinterlegt sind? Das sollte doch bei deinen Eltern/Großeltern ausreichen?

**Comment by p0rys** [comment]
@haumacher Leider zeigt mir die 7430 nur die Fake-Mobilnummer und nutzt diese entsprechend auch zum blocken. Ich habe nun doch die 01521* komplett blockiert, dass scheint erstmal den größten Teil abzufangen.

@nillebor Ich habe auch schon an eine Whitelist gedacht, jedoch fallen mir da zu viele mögliche Anrufer durchs Raster bzw. sind vorher nicht bekannt (Behörden, Krankenkassen, Rentenkassen etc.)
