### ISSUE TITLE
Android PeopleSync kein Adressbuch 

### ISSUE THREAD

**Issue by hem0773** [haumacher/phoneblock#71]
Hallo !
PeopleSync  legt diesen Nutzer an 
![image](https://github.com/haumacher/phoneblock/assets/57199067/2f176145-af8d-4bd1-808c-7ee285cdaa47)

Ein Adressbuch kann ich nicht finden 
![image](https://github.com/haumacher/phoneblock/assets/57199067/84b585a1-a232-4ecf-a0d9-8adc9c04767e)

**Comment by haumacher** [comment]
Sind Sie sicher, dass Sie bei der Konto-Einrichtung die richtige Einstellung ausgewählt haben:

![image](https://github.com/haumacher/phoneblock/assets/5607145/17535120-f4f7-4fba-bb73-fbf4b1d1c810)

**Comment by hem0773** [comment]
ja klar genau so,  Anleitung ist ja alles gut erklärt.
Auf dem Tablet ging es gleich und auf dem Handy war es heute morgen ohne das ich was geändert habe auch  
Also alles ok
