### ISSUE TITLE
No response from server 

### ISSUE THREAD

**Issue by gmueller-fr** [haumacher/phoneblock#72]
![Screenshot_20240510-161753](https://github.com/haumacher/phoneblock/assets/169467638/4afbb4fb-3b9b-4076-8b5f-61ea5e55725e)

**Comment by gatonero** [comment]
Ich habe die gleiche Meldung erhalten und folgende Datei.
[peoplesync-debug.zip](https://github.com/haumacher/phoneblock/files/15278579/peoplesync-debug.zip)

**Comment by haumacher** [comment]
Das sieht so aus wie #73 - bitte etwas Geduld, ich muss einen Fix vorbereiten...

**Comment by gmueller-fr** [comment]
Hallo,
ich benutze auch peoplesync auf dem Handy seit vielleicht einer Woche und habe die Meldung gerade zum ersten Mal bekommen. Bisher müssen wohl die Updates störungsfrei verlaufen sein. Auch ich habe die Datei peoplesync-debug.zip bekommen und mit der hier geposteten verglichen. Im Prinzip steht da dasselbe drin.

**EXCEPTION
at.bitfire.dav4jvm.exception.HttpException: HTTP 400** 

Ich habe es primär auf der Fritzbox installiert - dort wurde keine Fehlermeldung generiert - u.U. wurde auch kein Update der Daten zu diesem Zeitpunkt versucht ...

**Comment by haumacher** [comment]
Das Problem sollte behoben sein, bitte nochmal testen. Für eine Rückmeldung wäre ich dankbar. Lösung siehe #73.

**Comment by gmueller-fr** [comment]
Ich habe den sync manuell gestartet - keine Fehlermeldung. 😎 😁

Bernhard Haumacher ***@***.***> schrieb am Fr., 10. Mai 2024,
23:17:

**Comment by gatonero** [comment]
Auch ich habe die Synchronisierung manuell angestoßen. Es ist kein Fehler aufgetreten.
