### ISSUE TITLE
[Update Anleitung Android] Synchronisation via Davx5

### ISSUE THREAD

**Issue by nillebor** [haumacher/phoneblock#74]
Android-User welche bereits die [Davx5](https://www.davx5.com/) App aus dem [Playstore](https://play.google.com/store/apps/details?id=at.bitfire.davdroid), [F-Droid](https://f-droid.org/packages/at.bitfire.davdroid/) oder [Github](https://github.com/bitfireAT/davx5-ose/releases) nutzen, brauchen die PeopleSync-App nicht und können gleich mit der Anmeldung beginnen.

Ich nutze Davx5 seit 10 Jahren um meine Adressbücher und Kalender vom Heimserver zu synchronisieren.

![grafik](https://github.com/haumacher/phoneblock/assets/59985723/b5365505-44a3-4e75-93a7-43faeb496c53)
![grafik](https://github.com/haumacher/phoneblock/assets/59985723/71de2e3d-a53e-4e87-a245-c9dfb5c81ac7)
![grafik](https://github.com/haumacher/phoneblock/assets/59985723/286108db-ab33-4648-bff6-518b2bf6b842)
![grafik](https://github.com/haumacher/phoneblock/assets/59985723/34d1924b-904b-46ce-8746-d49b6403f396)
![grafik](https://github.com/haumacher/phoneblock/assets/59985723/a7ce4379-549e-48b2-8963-810b8eb0dc4f)
![grafik](https://github.com/haumacher/phoneblock/assets/59985723/d1693946-ff2a-4ae5-a2ba-b1b9571f9538)

Eventuell möchtest du ein Hinweis dazu in deiner Anleitung hinterlegen.

**Comment by nillebor** [comment]
Da wirst du den Entwickler fragen müssen. Diese checken die Apps in den Store und auf Github ein. Die Software selbst ist Open Source. Die Software aktualisiert nicht nur Adressbücher, sondern auch Kalender und kann auch einen WebDAV Account in den Dateimanager hinzufügen. Es gibt mehr Einstellmöglichkeiten und ist ein "Must-have" für jeden der Adressbücher oder Kalender Synchronisieren will. 

Für welche Version du dich entscheidest, ist egal. Bei den beiden Stores bekommst du die Updates über die Stores angezeigt und aktualisiert. Bei der Githubversion muss man immer manuell tätig werden. Ich selbst hatte damals die Version im Playstore gekauft, bin aber seit einiger Zeit ohne den G-Store und G-Services auf den Mobilgeräten (Custom ROM) unterwegs. Aus diesem Grund nutze ich F-Droid als Standard-Store. Dort sind alle meine benötigten Apps auch vorhanden gewesen (keine alternativen). 

Davx5 ist sehr weit verbreitet und sollte auch in der Anleitung aufgenommen werden. Nicht das einer auf den Gedanken kommt eine 2 App zusätzlich zu installieren ;)

**Comment by Revan335** [comment]
Der Preis im PlayStore gilt der Unterstützung der App/Entwickler und des Projekts.

Aber ja, auch ich Frage mich wieso DAVx5 nicht in der Anleitung steht.

Besonders da es das Github Repo was bspw. im Store für PeopleSync genannt wird, gar nicht mehr gibt.

**Comment by haumacher** [comment]
Danke für die Screenshots - ich habe einen Hinweis auf DAVx5 in der Installationsanleitung ergänzt. Wenn jemand das sowieso schon installiert hat, dann weiß er offensichtlich was er tut und wird die bestehende Anleitung sinngemäß übertragen können. Wenn nicht, dann ist zum Ausprobieren die kostenlose Variante gut genug.

Vgl. https://phoneblock.net/phoneblock/setup-android/
