### ISSUE TITLE
PB Anrufbeantworter Fehler 409

### ISSUE THREAD

**Issue by KobeLAL** [haumacher/phoneblock#75]
Hallo,

beim einrichten des DynDns bekomme ich den Fehler 409 No domain name set. Ist das ein Fehler der FritzBox (dann würde ich es AVM melden), oder stimmt da irgendetwas nicht?

**Comment by haumacher** [comment]
Hi, 

Du hast alle Felder mit Update-URL, Domainname usw. richtig ausgefüllt? Kannst Du einen Screen-Shot von Deiner DynDNS-Einstellungsseite machen? Gerne auch per E-Mail.

**Comment by haumacher** [comment]
> Der nicht registriert Fehler kommt beim drücken auf DynDNS überprüfen.
Ah ja klar, das heißt, dass keine IP-Informationen von Deiner Box bei PhoneBlock angekommen sind - das kann ich auch in der Datenbank nachvollziehen. Leider hat die Übermittlung des Screenshots per E-Mail nicht funktioniert. Könntest Du es nochmal direkt auf der GitHub-Seite probieren?

**Comment by KobeLAL** [comment]
Kann ich die Login Daten gefahrlos hier posten?

**Comment by KobeLAL** [comment]
AVM hat sich heute morgen bei mir gemeldet und weitere Infos angefordert. Es wurde der Entwicklungsabteilung weitergeleitet. Bin gespannt was rauskommt.

**Comment by KobeLAL** [comment]
Mit der neuen FritzOS 8.0 funktioniert die Einrichtung. Hoffe es bleibt so.
