### ISSUE TITLE
Blocklist ist leer

### ISSUE THREAD

**Issue by wfaust57** [haumacher/phoneblock#76]
Die Blocklist auf der Fritzbox ist leer und lässt sich nicht synchronisieren. Ich krieg immer Fehler Nummer 11.

**Comment by haumacher** [comment]
Siehe E-Mail. Sie scheinen ein Leerzeichen am Ende Ihres Benutzernamens bei der Einrichtung der Blockliste in der Fritz!Box eingegeben zu haben. Am besten die Kopierfunktion für Nutzernamen und Passwort auf der PhoneBlock-Webseite verwenden.
