### ISSUE TITLE
Fehlerhafte Anleitung für iPhones (iOS 17)

### ISSUE THREAD

**Issue by BKrnk1337** [haumacher/phoneblock#77]
Die Anleitung für die Installation des CardDAV Accounts auf dem iPhone ist so nicht ganz korrekt.
Mindestens mit iOS 17 haben sich hier die Menüpunkte im iPhone geändert.

**Bisher lautet diese wie folgt:**
Die Installation läuft in den folgenden Schritten:
1) Melde Dich bei PhoneBlock an.
2) Öffne "Einstellungen" - "Passwörter & Accounts".
3) Tippe auf "Account hinzufügen" - "Andere" > "CardDAV-Account hinzufügen".

**Jedoch müsste Punkt zwei wie folgt lautet:**
2) Öffne "Einstellungen" > "Kontakte" > "Accounts"
3) Tippe auf "Account hinzufügen" - "Andere" > "CardDAV-Account hinzufügen"

**Comment by haumacher** [comment]
Beschreibung angepasst: https://phoneblock.net/phoneblock/setup-iphone/
