### ISSUE TITLE
tuta.io domain gets marked as "temporary mail adress"

### ISSUE THREAD

**Issue by johnyb0y** [haumacher/phoneblock#84]
Hi, 

first of all: Thank you for this great project. 
I just wanted to give you a headsup that my primary mail adress, which uses `tuta.io` as domain, is denied for registration due to it being falsely recognized as a "temporary mail adress".
`tuta.io` is part of the german paid mail provider [Tuta](https://tuta.com/) (also knows as Tutanota).
I then used another mail which uses `tuta.com`, and it worked fine.

Kind regards
Johannes

**Comment by haumacher** [comment]
Thanks for your report, I removed the domain from the blocklist.
