### ISSUE TITLE
Fehler beim Einrichten vermeiden: Nutzername und Passwort mit Leerzeichen

### ISSUE THREAD

**Issue by haumacher** [haumacher/phoneblock#95]
Ein häufiger Fehler bei der Einrichtung ist es, dass Nutzer überflüssige Leerzeichen am Anfang oder Ende des Passworts oder Nutzernamens eingeben. Aktuell scheitert dann der Zugriffsverusch, weil diese nicht ignoriert werden. Besser wäre es, Leerzeichen im Nutzernamen und Passwort zu ignorieren, um solche Fehler zu vermeiden.

**Comment by hduelme** [comment]
Eine alternative wäre es eine Warnung anzuzeigen, wenn Leerzeichen vor/nach dem Nutzername oder dem Passwort stehen.

**Comment by haumacher** [comment]
Das Problem ist ja dass der Nutzer die Daten von der Webseite in seine Fritz!Box kopieren muss. Wenn er da was falsch macht, kann die Webseite keine Warnung mehr anzeigen. Das Problem fällt dann erst auf, wenn die Box mit Zugangsdaten ankommt, die nicht passen - und dann meldet die Box nur Fehler 11 oder sowas Bescheuertes. Und das allerbeste ist, dass man Zugangsdaten in der Box nicht mehr ändern kann, ohne das Telefonbuch nochmal zu löschen und neu anzulegen (ist jedenfalls mein Gefühl).

Was der CardDAV-Server aber machen kann, ist vor dem Check Leerzeichen um Nutzernamen und Passwort entfernen.

**Comment by haumacher** [comment]
Top, change ist live.
